@Api_HostAddress = http://localhost:5219

### Create User V1 using path
POST {{Api_HostAddress}}/api/v1/user
Content-Type: application/json

{
    "username": "John Doe",
    "email": "john.doe@example.com"
}

### Create User V1 using query string
GET {{Api_HostAddress}}/api/user/?version=1.0
Content-Type: application/json

{
    "username": "John Doe",
    "email": "John.Doe@example.com"
}

### Create User V1 using header
POST {{Api_HostAddress}}/api/user
Content-Type: application/json
X-Version: 1.0

{
    "username": "John Doe",
    "email": "John.Doe@example.com"
}

###
