@Api_HostAddress = http://localhost:5219

### Create User V1 using path
# @name createUserV1
POST {{Api_HostAddress}}/api/v1/user
Content-Type: application/json

{
    "username": "John Doe",
    "email": "john.doe@example.com"
}

###

@userId = {{createUserV1.response.body.$.user_id}}

## Get User V1 By Id
# @name getUserV1ById
GET {{Api_HostAddress}}/api/v1/user/{{userId}}

### 

### Create User V1 using query string
GET {{Api_HostAddress}}/api/user/?version=1.0
Content-Type: application/json

{
    "username": "John Doe",
    "email": "John.Doe@example.com"
}

### Create User V1 using header
POST {{Api_HostAddress}}/api/user
Content-Type: application/json
X-Version: 1.0

{
    "username": "John Doe",
    "email": "John.Doe@example.com"
}

###
